### ISSUE TITLE
Cant run the server

### ISSUE THREAD

**Issue by muhammadwafa** [Yashpk789987/Online-Dating-App#3]

**Comment by muhammadwafa** [comment]
Unhandled rejection SequelizeAccessDeniedError: Access denied for user 'saanviin_dating'@'103.28.132.98' (using password: YES)

**Comment by drsandeepjd** [comment]
It is still in development
change the database credientials to yout own mysql database

**Comment by Yashpk789987** [comment]
> Unhandled rejection SequelizeAccessDeniedError: Access denied for user 'saanviin_dating'@'103.28.132.98' (using password: YES)

It's still in development.
for database issue go to index.js in models folder and specify your own database credientials

**Comment by Yashpk789987** [comment]
This project is still in development
